#pragma once

// #include "IComponent.hpp"
// #include "AnimatedSprite.hpp"
#include "Effects.hpp"
#include "EffectsList.hpp"
#include "EntityStatus.hpp"
#include "Hitbox.hpp"
#include "MovementPattern.hpp"
#include "PlayerInput.hpp"
#include "SceneViewRenderer.hpp"
#include "Sprite.hpp"
#include "StatusModEvent.hpp"
#include "TeamTag.hpp"
#include "UpdateEntityEvent.hpp"
#include "UpdateEntityPolling.hpp"